### ISSUE TITLE
ionic project crashing after npm install (TypeError: Cannot read property 'glob' of null)

### ISSUE THREAD

**Issue by lmiguel-96** [ngx-rocket/generator-ngx-rocket#255]
## I'm submitting a...

[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request

## Current behavior

When I barely generate a project witch ionic, auth, and PWA, after npm install, when doing npm start, inmediately crash and throws: 
> guide-app@1.0.0 start /home/goku/Plantillas/guide-app
> npm run env -s && ng serve --aot --proxy-config proxy.conf.js

/home/goku/Plantillas/guide-app/node_modules/@ngtools/json-schema/src/schema-tree.js:226
                this._children[name] = this._createChildProperty(name, value ? value[name] : undefined, forward ? forward.children[name] : null, propertySchema);
                                                                                                                                  ^

TypeError: Cannot read property 'glob' of null
    at ObjectSchemaTreeNode._set (/home/goku/Plantillas/guide-app/node_modules/@ngtools/json-schema/src/schema-tree.js:226:131)
    at new ObjectSchemaTreeNode (/home/goku/Plantillas/guide-app/node_modules/@ngtools/json-schema/src/schema-tree.js:211:14)
    at OneOfSchemaTreeNode._createChildProperty (/home/goku/Plantillas/guide-app/node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
    at OneOfSchemaTreeNode._typesPrototype.schema.oneOf.map (/home/goku/Plantillas/guide-app/node_modules/@ngtools/json-schema/src/schema-tree.js:163:25)
    at Array.map (<anonymous>)
    at new OneOfSchemaTreeNode (/home/goku/Plantillas/guide-app/node_modules/@ngtools/json-schema/src/schema-tree.js:162:48)
    at ArraySchemaTreeNode._createChildProperty (/home/goku/Plantillas/guide-app/node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
    at ArraySchemaTreeNode._set (/home/goku/Plantillas/guide-app/node_modules/@ngtools/json-schema/src/schema-tree.js:288:39)
    at new ArraySchemaTreeNode (/home/goku/Plantillas/guide-app/node_modules/@ngtools/json-schema/src/schema-tree.js:269:14)
    at ObjectSchemaTreeNode._createChildProperty (/home/goku/Plantillas/guide-app/node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! guide-app@1.0.0 start: `npm run env -s && ng serve --aot --proxy-config proxy.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the guide-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/goku/.npm/_logs/2018-02-19T17_17_57_709Z-debug.log

## Environment

```
- generator version: 3.2.1
- node version: 8.9.4  <!-- run `node --version` -->
- npm version: 5.6.0  <!-- run `npm --version` -->
- OS:  Linux <!-- Mac, Linux, Windows -->
```

Others:

Xubuntu 17.10, VSCode.
This is my yo-rc.json: {
  "generator-ngx-rocket": {
    "version": "3.2.1",
    "props": {
      "appName": "guide-app",
      "target": [
        "web",
        "cordova"
      ],
      "pwa": true,
      "mobile": [
        "ios",
        "android"
      ],
      "ui": "ionic",
      "auth": true,
      "projectName": "guide-app",
      "packageManager": "npm"
    }
  }
}

Thanks for this awesome tool!

**Comment by sinedied** [comment]
seems like an issue occured during your npm install (I see this frequently these times on the CI), you should try removing your `node_modules` then reinstalling them:
```
rm -rf node_modules
npm i
```

**Comment by lmiguel-96** [comment]
I checked and yes, you are right, It was a problem with my setup of npm, I reinstalled, and it works perfect now.

Sorry for that, and thanks for the quick response.
