### ISSUE TITLE
Ionic pro - deploy

### ISSUE THREAD

**Issue by mhuntley** [ngx-rocket/generator-ngx-rocket#340]
We are looking to setup ionic pro within our project but we are having a few issues. Has anyone had any luck with this?

The issues we have faced are due to the folder structure. Ionic looks for src/app/main.ts but it is actually in src/main.ts. I am not able to find any configuration settings for this. If I move this file I then get this error which I am unable to resolve.

```

ionic-app-script task: "build" 
TypeError: Cannot read property 'kind' of undefined 
TypeError: Cannot read property 'kind' of undefined
    at declareSymbolAndAddToSymbolTable (/.../node_modules/typescript/lib/typescript.js:21251:31)
    at bindPropertyOrMethodOrAccessor (.../node_modules/typescript/lib/typescript.js:22225:19)
    at bindWorker (.../node_modules/typescript/lib/typescript.js:21778:28)
    at bind (.../node_modules/typescript/lib/typescript.js:21627:13)
    at bindSourceFile .../node_modules/typescript/lib/typescript.js:20036:17)
    at Object.bindSourceFile (.../node_modules/typescript/lib/typescript.js:19979:9)
    at initializeTypeChecker (.../node_modules/typescript/lib/typescript.js:47371:20)
    at Object.createTypeChecker (.../node_modules/typescript/lib/typescript.js:24920:9)
    at Object.getTypeChecker (.../node_modules/typescript/lib/typescript.js:74466:79)
    at moduleNameResolvesToAmbientModuleInNonModifiedFile (.../node_modules/typescript/lib/typescript.js:74222:88)

```

Any advise would be great.

**Comment by sinedied** [comment]
The Ionic CLI cannot build Angular CLI project (seems that it's what you're trying to do from your error), but you don't need the Ionic CLI to use Ionic pro, see: https://ionicframework.com/docs/pro/deploy/builds/

Their build system juste use the `npm run build` script and expect an output `www` folder, so that should work.

**Comment by mhuntley** [comment]
The issue was because we did not have the project in the root folder of our repo and the combination of that and not using the ionic cli was causing me problems.

Thanks for your help.
