### ISSUE TITLE
ngx update failed in .yo-rc.json

### ISSUE THREAD

**Issue by Paul75** [ngx-rocket/generator-ngx-rocket#406]
## I'm submitting a...
- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Minimal reproduction of the problem with instructions
I do ngw update and after chose 'a' and got error : 
```
Updating pop client project (5.2.0 -> 5.3.0)

Make sure you don't have uncommitted changes before overwriting files!
 conflict package.json
? Overwrite package.json? overwrite this and all others
    force package.json
(node:20376) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, open 'C:\www\POP\pop-client\.yo-rc.json'
    at Object.openSync (fs.js:436:3)
    at Object.writeFileSync (fs.js:1187:35)
    at write (C:\laragon\bin\nodejs\node-v10.13.0-win-x64\node_modules\generator-ngx-rocket\node_modules\mem-fs-editor\lib\actions\commit.js:14:6)
    at DestroyableTransform._transform (C:\laragon\bin\nodejs\node-v10.13.0-win-x64\node_modules\generator-ngx-rocket\node_modules\mem-fs-editor\lib\actions\commit.js:43:7)
    at DestroyableTransform.Transform._read (C:\laragon\bin\nodejs\node-v10.13.0-win-x64\node_modules\generator-ngx-rocket\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\laragon\bin\nodejs\node-v10.13.0-win-x64\node_modules\generator-ngx-rocket\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\laragon\bin\nodejs\node-v10.13.0-win-x64\node_modules\generator-ngx-rocket\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\laragon\bin\nodejs\node-v10.13.0-win-x64\node_modules\generator-ngx-rocket\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (C:\laragon\bin\nodejs\node-v10.13.0-win-x64\node_modules\generator-ngx-rocket\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at DestroyableTransform.ondata (C:\laragon\bin\nodejs\node-v10.13.0-win-x64\node_modules\generator-ngx-rocket\node_modules\readable-stream\lib\_stream_readable.js:619:20)
(node:20376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Environment

```
- generator version: 5.3.0
- node version: 11.0.0
- npm version: 6.4.1
- OS:  Windows 10
```

**Comment by Paul75** [comment]
It becasue files are cached (windows cached thsi files)
