### ISSUE TITLE
Something wrong on Logger service

### ISSUE THREAD

**Issue by thiagog3** [ngx-rocket/generator-ngx-rocket#80]
I just installed using yeoman command and started using npm start. But in browser nothing shows and I received this error:

`ERROR TypeError: Illegal invocation
    at Logger.webpackJsonp.58.Logger.log (http://localhost:4200/main.bundle.js:1806:18)
    at Logger.webpackJsonp.58.Logger.debug (http://localhost:4200/main.bundle.js:1767:14)
    at AppComponent.webpackJsonp.287.AppComponent.ngOnInit (http://localhost:4200/main.bundle.js:846:13)
    at checkAndUpdateDirectiveInline (http://localhost:4200/vendor.bundle.js:11025:19)
    at checkAndUpdateNodeInline (http://localhost:4200/vendor.bundle.js:12448:17)
    at checkAndUpdateNode (http://localhost:4200/vendor.bundle.js:12387:16)
    at debugCheckAndUpdateNode (http://localhost:4200/vendor.bundle.js:13090:59)
    at debugCheckDirectivesFn (http://localhost:4200/vendor.bundle.js:13031:13)
    at Object.eval [as updateDirectives] (ng:///AppModule/AppComponent_Host.ngfactory.js:17:5)
    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:4200/vendor.bundle.js:13016:21)`

Anybody with the same issue?

**Comment by sinedied** [comment]
Which browser/version are you using?

In `app/core/logger.service.ts`, try replacing:
```ts
 private log(func: Function, level: LogLevel, objects: any[]) {
    if (level <= Logger.level) {
      const log = this.source ? ['[' + this.source + ']'].concat(objects) : objects;
      func.apply(func, log);
      Logger.outputs.forEach((output) => output.apply(output, [this.source, level].concat(objects)));
    }
  }
```

with
```ts
  private log(func: Function, level: LogLevel, objects: any[]) {
    if (level <= Logger.level) {
      const log = this.source ? ['[' + this.source + ']'].concat(objects) : objects;
      func.apply(console, log);
      Logger.outputs.forEach((output) => output.apply(output, [this.source, level].concat(objects)));
    }
  }
```
Tell me if it solves your issue.

Seems like some versions of Firefox have this [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=989619),

**Comment by thiagog3** [comment]
@sinedied sorry about the time gap! I tried replace like you said before and everything works OK! 

I don't know if is a browser issue because I tested on Firefox and Chrome (last version) and occours the same result. I'm using node 6.9.1 and Ubuntu. When I test without change anything on my mac i haven't problems.

Can it be a problem with some dependence?

**Comment by sinedied** [comment]
Thanks for the feedback! It's strange that it works differently depending of the platform, it may be related to the underlying implementation of the native `console` object.
Anyway, I'll integrate the patch in a PR since it seems some browsers on Windows also have the issue.
